name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write       # required by actions/deploy-pages to create a Pages deployment
  id-token: write    # required by actions/configure-pages
  actions: read      # required by actions/deploy-pages to fetch artifacts from this run
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: 'pages'
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Debug environment
        run: |
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_SHA: ${{ github.sha }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

      - name: Debug deployment
        if: failure()
        run: |
          echo "Deployment failed. Check if GitHub Pages is enabled and configured correctly."
          echo "Ensure the repository has a valid GitHub Pages source."

# Для публикации убедитесь, что в настройках репозитория включен GitHub Pages и выбран source: GitHub Actions
